apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskapp

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: backend

      containers:
        - name: backend
          image: ghcr.io/ts-a-devops/taskapp-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: taskapp
            - name: DATABASE_USER
              value: taskapp_admin
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: taskapp-secret
                  key: SECRET_KEY
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: PORT
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: taskapp-config
                  key: FLASK_ENV
          startupProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

