apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskapp-ingress
  namespace: taskapp
  annotations:
    argocd.argoproj.io/tracking-id: taskapp-gitops:networking.k8s.io/Ingress:taskapp/taskapp-ingress
spec:
  # ⚡ The mandatory structural field that tells Traefik to process this Ingress
  ingressClassName: traefik
  rules:
    - host: taskapp.51.20.43.134.sslip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
