apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: taskapp-ingressroute
  namespace: taskapp
  annotations:
    argocd.argoproj.io/tracking-id: taskapp-gitops:traefik.io/IngressRoute:taskapp/taskapp-ingressroute
spec:
  entryPoints:
    - web # Handles http:// traffic on Port 80
    - websecure # Handles https:// traffic on Port 443
  routes:
    # 1. API Route
    - match: Host(`taskapp.51.20.43.134.sslip.io`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: backend
          port: 5000
    # 2. Frontend User Interface Route
    - match: Host(`taskapp.51.20.43.134.sslip.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 80
